Autodoc fix + DL landing page
lava-nc/lava-docs pull request #6
Opened 2021-11-09 16:53 UTC by bamsumit

2021-11-10 18:40 UTC, mgkwill commented on README.md
>  ```bash
Can we change this to "Test Doc Build"

2021-11-10 18:43 UTC, mgkwill requested changes
This looks pretty good to me.

Please add `project.plugin_depends_on("nbsphinx")` to build.py: 34 and address the redundancy of "generation" in the readme.

For the CI build I probably need to add pull of lava and lib code to ensure it builds correctly.

2021-11-10 18:44 UTC, mgkwill commented on README.md
>  pyb sphinx_generate_documentation
Can we change this to "Test Doc Build"

2021-11-10 21:02 UTC, bamsumit commented
@mgkwill: addressed your comments. Also added scripts to sync notebooks and render notebooks.

2021-11-11 02:31 UTC, awintel approved these changes
Thanks

2021-11-11 03:47 UTC, mgkwill approved these changes

2021-11-11 03:47 UTC, merged